import Footer from "@/component/Footer/Footer";
import Navbar from "@/component/Navbar/Navbar";
import { Inter } from "next/font/google";
import { Themeprovider } from "./context/ThemeContext";
import "./globals.css";
import styles from "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "HEXASHOP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Themeprovider>
        <div className="container">
          <Navbar />
          {children}
          <Footer />
        </div>
      </Themeprovider>
      </body>
    </html>
  );
}
